# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: [ "network/gRPC-jwt" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Configure NUGET
        run: dotnet nuget add source --username "${{ github.actor }}" --password "${{ secrets.PAT_TOKEN }}" --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/exriba/index.json" 

      - name: Restore
        run: dotnet restore

      - name: Build    
        run: dotnet build --configuration Release --no-restore

      # Upload the compiled files so the Test job can use them
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./**/bin/Release/
          
  test:
    runs-on: ubuntu-latest
    needs: build # Ensures this job only runs after 'build' succeeds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Configure NUGET
        run: dotnet nuget add source --username "${{ github.actor }}" --password "${{ secrets.PAT_TOKEN }}" --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/exriba/index.json" 

      # Download the binaries from the Build job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run Tests
        run: dotnet test --configuration Release --logger "trx" --results-directory ./TestResults

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: "TestResults/*.trx"
          reporter: dotnet-trx
          github_token: "${{ secrets.PAT_TOKEN }}"
